["protostar.config"]
protostar_version = "0.3.1"

["protostar.project"]
libs_path = "lib"

[profile.ci.protostar.shared_command_configs]
no_color = true

[profile.local.protostar.deploy]
gateway_url = "http://127.0.0.1:5050/"
feeder_gateway_url = "http://127.0.0.1:5050/"
network = "alpha-goerli"
network_opt = "--network alpha-goerli --gateway_url http://127.0.0.1:5050 --feeder_gateway_url http://127.0.0.1:5050"

[profile.staging.protostar.deploy]
network = "alpha-goerli"
network_opt = "--network alpha-goerli"

[profile.prod.protostar.deploy]
network = "alpha-goerli"
network_opt = "--network alpha-goerli"

["protostar.shared_command_configs"]
cairo_path = ["contracts", "lib/cairo_contracts/src", "lib/cairo_streams/src"]

["protostar.test"]
target = ["contracts"]

["protostar.contracts"]
registry = ["./contracts/onlydust/deathnote/core/registry/registry.cairo"]
profile = ["./contracts/onlydust/deathnote/core/profile/profile.cairo"]
contributions = [
    "./contracts/onlydust/deathnote/core/contributions/contributions.cairo",
]
contributions_migration = [
    "./contracts/onlydust/deathnote/core/contributions/contributions_migration.cairo",
]
proxy = ["./lib/cairo_contracts/src/openzeppelin/upgrades/Proxy.cairo"]
