["protostar.config"]
protostar_version = "0.2.6"

["protostar.project"]
libs_path = "lib"

[profile.ci.protostar.shared_command_configs]
no_color=true

[profile.testnet.protostar.deploy]
network="alpha-goerli"

[profile.mainnet.protostar.deploy]
network="alpha-mainnet"

["protostar.shared_command_configs"]
cairo_path = ["contracts", "lib/cairo_contracts/src", "lib/cairo_streams/src"]

["protostar.test"]
target = ["contracts"]

["protostar.contracts"]
registry = [ "./contracts/onlydust/deathnote/core/registry/registry.cairo" ]
profile = [ "./contracts/onlydust/deathnote/core/profile/profile.cairo" ]
contributions = [ "./contracts/onlydust/deathnote/core/contributions/contributions.cairo" ]
proxy = [ "./lib/cairo_contracts/src/openzeppelin/upgrades/Proxy.cairo" ]
