["protostar.config"]
protostar_version = "0.5.0"

["protostar.project"]
libs_path = "lib"

[profile.ci.protostar.shared_command_configs]
no_color = true

[profile.local.protostar.deploy]
gateway_url = "http://127.0.0.1:5050/"
feeder_gateway_url = "http://127.0.0.1:5050/"
network = "alpha-goerli"
network_opt = "--network alpha-goerli --gateway_url http://127.0.0.1:5050 --feeder_gateway_url http://127.0.0.1:5050"

[profile.staging.protostar.deploy]
network = "alpha-goerli"
network_opt = "--network alpha-goerli"

[profile.prod.protostar.deploy]
network = "alpha-goerli"
network_opt = "--network alpha-goerli"

["protostar.shared_command_configs"]
cairo_path = ["contracts", "lib/cairo_contracts/src", "lib/cairo_streams/src"]

["protostar.test"]
target = ["contracts"]

["protostar.contracts"]
contributions = [
    "./contracts/onlydust/marketplace/core/contributions/contributions.cairo",
]
contributions_migration = [
    "./contracts/onlydust/marketplace/core/contributions/contributions_migration.cairo",
]
proxy = ["./lib/cairo_contracts/src/openzeppelin/upgrades/presets/Proxy.cairo"]
github_contribution = [
    "./contracts/onlydust/marketplace/core/github/contribution.cairo",
]

# New contributions
contribution = ["./contracts/onlydust/marketplace/core/contribution.cairo"]

# Strategies
access_control = [
    "./contracts/onlydust/marketplace/core/assignment_strategies/access_control.cairo",
]
closable = [
    "./contracts/onlydust/marketplace/core/assignment_strategies/closable.cairo",
]
composite = [
    "./contracts/onlydust/marketplace/core/assignment_strategies/composite.cairo",
]
gated = [
    "./contracts/onlydust/marketplace/core/assignment_strategies/gated.cairo",
]
